version: "3.8"

services:
    postgres:
        image: postgres:17.2-alpine
        container_name: go_postgres
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: docker
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped

    redis:
        image: redis:7.4-alpine
        container_name: go_redis
        command: ["redis-server", "--requirepass", "docker"]
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        restart: unless-stopped

volumes:
    postgres-data:
    redis-data:
