import type { Metadata } from "next";
import { Geist_Mono, DM_Sans, EB_Garamond } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";

const DMSans = DM_Sans({
    variable: "--font-dm-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const ebGaramond = EB_Garamond({
    variable: "--font-eb-garamond",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${geistMono.variable} ${DMSans.variable} ${ebGaramond.variable} antialiased font-sans`}
            >
                {children}
                <Toaster />
            </body>
        </html>
    );
}
